platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet

inputs:
- name: dotnet-core-helloWorld

run:
  path: sh
  args: ["dotnet-core-helloWorld/ci/tasks/build.sh"]
